apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mvp-k8s-statefulset
  namespace: mvp-k8s-namespace-dev
spec:
  serviceName: "my-app"
  replicas: 3
  selector:
    matchLabels:
      app: mvp-k8s-app1
  template:
    metadata:
      labels:
        app: mvp-k8s-app1
    spec:
      containers:
      - name: mvp-k8s-app1-container
        image: mvp-k8s-app1-image:latest
        ports:
        - containerPort: 80
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
