apiVersion: v1
kind: PersistentVolume
metadata:
  name: mvp-k8s-pv
  labels:
    app: mvp-k8s-app1
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: <NFS-Server-IP>
    path: /path/to/nfs/share
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
