apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mvp-k8s-replicaset
  namespace: mvp-k8s-namespace-dev
  labels:
    app: mvp-k8s-app1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mvp-k8s-app1
  template:
    metadata:
      labels:
        app: mvp-k8s-app1
    spec:
      containers:
      - name: mvp-k8s-app1-container
        image: mvp-k8s-app1-image:latest
        ports:
        - containerPort: 80
