apiVersion: v1
kind: Pod
metadata:
  name: mvp-k8s-secret-pod
  namespace: mvp-k8s-namespace-dev
spec:
  containers:
  - name: mvp-k8s-app1-container
    image: mvp-k8s-app1-image:latest
    env:
      - name: MY_USERNAME
        valueFrom:
          secretKeyRef:
            name: my-secret
            key: username
      - name: MY_PASSWORD
        valueFrom:
          secretKeyRef:
            name: my-secret
            key: password
  labels:
    app: my-app
